before_script:
- docker build -t "aut-$DOCKERFILE" -f "dockerfiles/$DOCKERFILE" .
env:
- DOCKERFILE=centos7 PRE=pip PRODUCT=ansible VERSION=2.8.15
- DOCKERFILE=centos7 PRE=pip PRODUCT=ansible VERSION=2.9.13
- DOCKERFILE=centos7 PRE=pip PRODUCT=ansible-base VERSION=2.10.1rc3
- DOCKERFILE=centos7 PRE=tar PRODUCT=ansible VERSION=2.8.15
- DOCKERFILE=centos7 PRE=tar PRODUCT=ansible VERSION=2.9.13
- DOCKERFILE=centos7 PRE=tar PRODUCT=ansible-base VERSION=2.10.1rc3
- DOCKERFILE=centos7 PRE=rpm PRODUCT=ansible VERSION=2.8.15
- DOCKERFILE=centos7 PRE=rpm PRODUCT=ansible VERSION=2.9.13
- DOCKERFILE=centos8 PRE=pip PRODUCT=ansible VERSION=2.8.15
- DOCKERFILE=centos8 PRE=pip PRODUCT=ansible VERSION=2.9.13
- DOCKERFILE=centos8 PRE=pip PRODUCT=ansible-base VERSION=2.10.1rc3
- DOCKERFILE=centos8 PRE=tar PRODUCT=ansible VERSION=2.8.15
- DOCKERFILE=centos8 PRE=tar PRODUCT=ansible VERSION=2.9.13
- DOCKERFILE=centos8 PRE=tar PRODUCT=ansible-base VERSION=2.10.1rc3
- DOCKERFILE=ubuntu2004 PRE=pip PRODUCT=ansible VERSION=2.8.15
- DOCKERFILE=ubuntu2004 PRE=pip PRODUCT=ansible VERSION=2.9.13
- DOCKERFILE=ubuntu2004 PRE=pip PRODUCT=ansible-base VERSION=2.10.1rc3
- DOCKERFILE=ubuntu2004 PRE=tar PRODUCT=ansible VERSION=2.8.15
- DOCKERFILE=ubuntu2004 PRE=tar PRODUCT=ansible VERSION=2.9.13
- DOCKERFILE=ubuntu2004 PRE=tar PRODUCT=ansible-base VERSION=2.10.1rc3
- DOCKERFILE=ubuntu1804 PRE=pip PRODUCT=ansible VERSION=2.8.15
- DOCKERFILE=ubuntu1804 PRE=pip PRODUCT=ansible VERSION=2.9.13
- DOCKERFILE=ubuntu1804 PRE=pip PRODUCT=ansible-base VERSION=2.10.1rc3
- DOCKERFILE=ubuntu1804 PRE=tar PRODUCT=ansible VERSION=2.8.15
- DOCKERFILE=ubuntu1804 PRE=tar PRODUCT=ansible VERSION=2.9.13
- DOCKERFILE=ubuntu1804 PRE=tar PRODUCT=ansible-base VERSION=2.10.1rc3
- DOCKERFILE=ubuntu1804 PRE=ppa PRODUCT=ansible VERSION=2.8.15 PPA=ansible/ansible-2.8
- DOCKERFILE=ubuntu1804 PRE=ppa PRODUCT=ansible VERSION=2.9.13 PPA=ansible/ansible-2.9
- DOCKERFILE=ubuntu1804 PRE=ppa PRODUCT=ansible VERSION=2.9.13 PPA=ansible/ansible
notifications:
  webhooks:
  - if: type != cron
    urls:
    - https://sl.da.gd/travisci?channel=%23relrodtest
  - if: type == cron
    on_cancel: never
    on_error: change
    on_failure: change
    on_success: change
    urls:
    - https://sl.da.gd/travisci?channel=%23relrodtest
script:
- docker run -t -e PYTHONPATH="/opt/pre/$PRODUCT-$VERSION/lib" -e PRE="$PRE" -e PRODUCT="$PRODUCT"
  -e VERSION="$VERSION" -e PPA="$PPA" "aut-$DOCKERFILE"
services:
- docker

