jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Build container image
      run: docker build -t "aut-${{ matrix.dockerfile }}" -f "dockerfiles/${{ matrix.dockerfile
        }}" .
    - name: Run tests
      run: docker run -t -e PYTHONPATH="/opt/pre/${{ matrix.product }}-${{ matrix.version
        }}/lib" -e PRE="${{ matrix.pre }}" -e PRODUCT="${{ matrix.product }}" -e VERSION="${{
        matrix.version }}" -e PPA="${{ matrix.ppa }}" "aut-${{ matrix.dockerfile }}"
    strategy:
      fail-fast: false
      matrix:
        include:
        - dockerfile: centos7
          pre: pip
          product: ansible
          version: 2.8.18
        - dockerfile: centos7
          pre: pip
          product: ansible
          version: 2.9.16
        - dockerfile: centos7
          pre: pip
          product: ansible-base
          version: 2.10.4
        - dockerfile: centos7
          pre: tar
          product: ansible
          version: 2.8.18
        - dockerfile: centos7
          pre: tar
          product: ansible
          version: 2.9.16
        - dockerfile: centos7
          pre: tar
          product: ansible-base
          version: 2.10.4
        - dockerfile: centos7
          pre: rpm
          product: ansible
          version: 2.8.18
        - dockerfile: centos7
          pre: rpm
          product: ansible
          version: 2.9.16
        - dockerfile: centos8
          pre: pip
          product: ansible
          version: 2.8.18
        - dockerfile: centos8
          pre: pip
          product: ansible
          version: 2.9.16
        - dockerfile: centos8
          pre: pip
          product: ansible-base
          version: 2.10.4
        - dockerfile: centos8
          pre: tar
          product: ansible
          version: 2.8.18
        - dockerfile: centos8
          pre: tar
          product: ansible
          version: 2.9.16
        - dockerfile: centos8
          pre: tar
          product: ansible-base
          version: 2.10.4
        - dockerfile: ubi7
          pre: pip
          product: ansible
          version: 2.8.18
        - dockerfile: ubi7
          pre: pip
          product: ansible
          version: 2.9.16
        - dockerfile: ubi7
          pre: pip
          product: ansible-base
          version: 2.10.4
        - dockerfile: ubi7
          pre: tar
          product: ansible
          version: 2.8.18
        - dockerfile: ubi7
          pre: tar
          product: ansible
          version: 2.9.16
        - dockerfile: ubi7
          pre: tar
          product: ansible-base
          version: 2.10.4
        - dockerfile: ubi7
          pre: rpm
          product: ansible
          version: 2.8.18
        - dockerfile: ubi7
          pre: rpm
          product: ansible
          version: 2.9.16
        - dockerfile: ubi8
          pre: pip
          product: ansible
          version: 2.8.18
        - dockerfile: ubi8
          pre: pip
          product: ansible
          version: 2.9.16
        - dockerfile: ubi8
          pre: pip
          product: ansible-base
          version: 2.10.4
        - dockerfile: ubi8
          pre: tar
          product: ansible
          version: 2.8.18
        - dockerfile: ubi8
          pre: tar
          product: ansible
          version: 2.9.16
        - dockerfile: ubi8
          pre: tar
          product: ansible-base
          version: 2.10.4
        - dockerfile: ubuntu2004
          pre: pip
          product: ansible
          version: 2.8.18
        - dockerfile: ubuntu2004
          pre: pip
          product: ansible
          version: 2.9.16
        - dockerfile: ubuntu2004
          pre: pip
          product: ansible-base
          version: 2.10.4
        - dockerfile: ubuntu2004
          pre: tar
          product: ansible
          version: 2.8.18
        - dockerfile: ubuntu2004
          pre: tar
          product: ansible
          version: 2.9.16
        - dockerfile: ubuntu2004
          pre: tar
          product: ansible-base
          version: 2.10.4
        - dockerfile: ubuntu1804
          pre: pip
          product: ansible
          version: 2.8.18
        - dockerfile: ubuntu1804
          pre: pip
          product: ansible
          version: 2.9.16
        - dockerfile: ubuntu1804
          pre: pip
          product: ansible-base
          version: 2.10.4
        - dockerfile: ubuntu1804
          pre: tar
          product: ansible
          version: 2.8.18
        - dockerfile: ubuntu1804
          pre: tar
          product: ansible
          version: 2.9.16
        - dockerfile: ubuntu1804
          pre: tar
          product: ansible-base
          version: 2.10.4
        - PPA: ansible/ansible-2.8
          dockerfile: ubuntu1804
          pre: ppa
          product: ansible
          version: 2.8.18
        - PPA: ansible/ansible-2.9
          dockerfile: ubuntu1804
          pre: ppa
          product: ansible
          version: 2.9.16
        - PPA: ansible/ansible-2.10
          dockerfile: ubuntu1804
          pre: ppa
          product: ansible-base
          version: 2.10.4
        - PPA: ansible/ansible
          dockerfile: ubuntu1804
          pre: ppa
          product: ansible
          version: 2.9.16
        - PPA: ansible/ansible
          dockerfile: ubuntu1804
          pre: ppa
          product: ansible-base
          version: 2.10.4
    timeout-minutes: 20
  macos-build:
    runs-on: ${{ matrix.dockerfile }}
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - env:
        PPA: ${{ matrix.ppa }}
        PRE: ${{ matrix.pre }}
        PRODUCT: ${{ matrix.product }}
        VERSION: ${{ matrix.version }}
      name: Run tests
      run: bash entrypoint.sh
    strategy:
      fail-fast: false
      matrix:
        include:
        - dockerfile: macos-10.15
          pre: pip
          product: ansible
          version: 2.9.16
        - dockerfile: macos-10.15
          pre: pip
          product: ansible-base
          version: 2.10.4
        - dockerfile: macos-10.15
          pre: tar
          product: ansible
          version: 2.9.16
        - dockerfile: macos-10.15
          pre: tar
          product: ansible-base
          version: 2.10.4
    timeout-minutes: 20
name: Ansible User Artifact Tests
'on':
  pull_request: null
  push: null
  schedule:
  - cron: 0 0 * * *

