jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Build container image
      run: docker build -t "aut-${{ matrix.dockerfile }}" -f "dockerfiles/${{ matrix.dockerfile
        }}" .
    - name: Run tests
      run: docker run -t -e PYTHONPATH="/opt/pre/${{ matrix.product }}-${{ matrix.version
        }}/lib" -e PRE="${{ matrix.pre }}" -e PRODUCT="${{ matrix.product }}" -e VERSION="${{
        matrix.version }}" -e PPA="${{ matrix.ppa }}" "aut-${{ matrix.dockerfile }}"
    strategy:
      fail-fast: false
      matrix:
        include:
        - dockerfile: centos7
          pre: pip
          product: ansible
          version: 2.8.18rc1
        - dockerfile: centos7
          pre: pip
          product: ansible
          version: 2.9.16rc1
        - dockerfile: centos7
          pre: pip
          product: ansible-base
          version: 2.10.4rc1
        - dockerfile: centos7
          pre: tar
          product: ansible
          version: 2.8.18rc1
        - dockerfile: centos7
          pre: tar
          product: ansible
          version: 2.9.16rc1
        - dockerfile: centos7
          pre: tar
          product: ansible-base
          version: 2.10.4rc1
        - dockerfile: centos8
          pre: pip
          product: ansible
          version: 2.8.18rc1
        - dockerfile: centos8
          pre: pip
          product: ansible
          version: 2.9.16rc1
        - dockerfile: centos8
          pre: pip
          product: ansible-base
          version: 2.10.4rc1
        - dockerfile: centos8
          pre: tar
          product: ansible
          version: 2.8.18rc1
        - dockerfile: centos8
          pre: tar
          product: ansible
          version: 2.9.16rc1
        - dockerfile: centos8
          pre: tar
          product: ansible-base
          version: 2.10.4rc1
        - dockerfile: ubuntu2004
          pre: pip
          product: ansible
          version: 2.8.18rc1
        - dockerfile: ubuntu2004
          pre: pip
          product: ansible
          version: 2.9.16rc1
        - dockerfile: ubuntu2004
          pre: pip
          product: ansible-base
          version: 2.10.4rc1
        - dockerfile: ubuntu2004
          pre: tar
          product: ansible
          version: 2.8.18rc1
        - dockerfile: ubuntu2004
          pre: tar
          product: ansible
          version: 2.9.16rc1
        - dockerfile: ubuntu2004
          pre: tar
          product: ansible-base
          version: 2.10.4rc1
        - dockerfile: ubuntu1804
          pre: pip
          product: ansible
          version: 2.8.18rc1
        - dockerfile: ubuntu1804
          pre: pip
          product: ansible
          version: 2.9.16rc1
        - dockerfile: ubuntu1804
          pre: pip
          product: ansible-base
          version: 2.10.4rc1
        - dockerfile: ubuntu1804
          pre: tar
          product: ansible
          version: 2.8.18rc1
        - dockerfile: ubuntu1804
          pre: tar
          product: ansible
          version: 2.9.16rc1
        - dockerfile: ubuntu1804
          pre: tar
          product: ansible-base
          version: 2.10.4rc1
    timeout-minutes: 20
name: Ansible User Artifact Tests
'on':
  pull_request: null
  push: null
  schedule:
  - cron: 0 0 * * *

