jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Build container image
      run: docker build -t "aut-${{ matrix.dockerfile }}" -f "dockerfiles/${{ matrix.dockerfile
        }}" .
    - name: Run tests
      run: docker run -t -e PYTHONPATH="/opt/pre/${{ matrix.product }}-${{ matrix.version
        }}/lib" -e PRE="${{ matrix.pre }}" -e PRODUCT="${{ matrix.product }}" -e VERSION="${{
        matrix.version }}" -e PPA="${{ matrix.ppa }}" "aut-${{ matrix.dockerfile }}"
    strategy:
      matrix:
        include:
        - dockerfile: centos7
          pre: pip
          product: ansible
          version: 2.8.17
        - dockerfile: centos7
          pre: pip
          product: ansible
          version: 2.9.15
        - dockerfile: centos7
          pre: pip
          product: ansible-base
          version: 2.10.3
        - dockerfile: centos7
          pre: tar
          product: ansible
          version: 2.8.17
        - dockerfile: centos7
          pre: tar
          product: ansible
          version: 2.9.15
        - dockerfile: centos7
          pre: tar
          product: ansible-base
          version: 2.10.3
        - dockerfile: centos7
          pre: rpm
          product: ansible
          version: 2.8.17
        - dockerfile: centos7
          pre: rpm
          product: ansible
          version: 2.9.15
        - dockerfile: centos8
          pre: pip
          product: ansible
          version: 2.8.17
        - dockerfile: centos8
          pre: pip
          product: ansible
          version: 2.9.15
        - dockerfile: centos8
          pre: pip
          product: ansible-base
          version: 2.10.3
        - dockerfile: centos8
          pre: tar
          product: ansible
          version: 2.8.17
        - dockerfile: centos8
          pre: tar
          product: ansible
          version: 2.9.15
        - dockerfile: centos8
          pre: tar
          product: ansible-base
          version: 2.10.3
        - dockerfile: ubuntu2004
          pre: pip
          product: ansible
          version: 2.8.17
        - dockerfile: ubuntu2004
          pre: pip
          product: ansible
          version: 2.9.15
        - dockerfile: ubuntu2004
          pre: pip
          product: ansible-base
          version: 2.10.3
        - dockerfile: ubuntu2004
          pre: tar
          product: ansible
          version: 2.8.17
        - dockerfile: ubuntu2004
          pre: tar
          product: ansible
          version: 2.9.15
        - dockerfile: ubuntu2004
          pre: tar
          product: ansible-base
          version: 2.10.3
        - dockerfile: ubuntu1804
          pre: pip
          product: ansible
          version: 2.8.17
        - dockerfile: ubuntu1804
          pre: pip
          product: ansible
          version: 2.9.15
        - dockerfile: ubuntu1804
          pre: pip
          product: ansible-base
          version: 2.10.3
        - dockerfile: ubuntu1804
          pre: tar
          product: ansible
          version: 2.8.17
        - dockerfile: ubuntu1804
          pre: tar
          product: ansible
          version: 2.9.15
        - dockerfile: ubuntu1804
          pre: tar
          product: ansible-base
          version: 2.10.3
        - PPA: ansible/ansible-2.8
          dockerfile: ubuntu1804
          pre: ppa
          product: ansible
          version: 2.8.17
        - PPA: ansible/ansible-2.9
          dockerfile: ubuntu1804
          pre: ppa
          product: ansible
          version: 2.9.15
        - PPA: ansible/ansible-2.10
          dockerfile: ubuntu1804
          pre: ppa
          product: ansible-base
          version: 2.10.3
        - PPA: ansible/ansible
          dockerfile: ubuntu1804
          pre: ppa
          product: ansible
          version: 2.9.15
        - PPA: ansible/ansible
          dockerfile: ubuntu1804
          pre: ppa
          product: ansible-base
          version: 2.10.3
    timeout-minutes: 20
name: Ansible User Artifact Tests
'on':
- push
- pull_request

